---
driver:
  name: docker
  use_sudo: false
  customize:
    memory 1048

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

verifier:
  name: inspec
  format: doc
  sudo_command: '. /etc/profile;'

platforms:
  - name: ubuntu-14.04
    driver_config:
      instance_name: kraken-ubuntu1404

suites:
  - name: default
    run_list:
      - recipe[kraken::default]
    attributes:
