---
driver:
  name: docker
  use_sudo: false
  customize:
    memory 1048

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

verifier:
  name: inspec
  sudo_command: '. /etc/profile;'

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[Kraken::default]
    attributes:
