name 'kraken'
maintainer 'Eagle genomics'
maintainer_email 'chef@eaglegenomics.com'
license 'apache2'
description 'Installs/Configures kraken'
long_description 'Installs/Configures kraken'
version '0.1.5'

source_url 'https://github.com/EagleGenomics-cookbooks/kraken'
issues_url 'https://github.com/EagleGenomics-cookbooks/kraken/issues'

depends 'apt'
depends 'build-essential'
depends 'magic_shell'
depends 'git'
depends 'Jellyfish'
