name 'Kraken'
maintainer 'Eagle genomics'
maintainer_email 'chef@eaglegenomics.com'
license 'apache2'
description 'Installs/Configures Kraken'
long_description 'Installs/Configures Kraken'
version '0.1.0'

depends 'build-essential'
depends 'magic_shell'
depends 'git'
